language: csharp
solution: FSharp.Data.JsonPath.sln
dotnet: 2.1.300
install:
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore
script:
  - dotnet restore
  - msbuild /p:Configuration=Release FSharp.Data.JsonPath.sln
  - mono ./packages/NUnit.ConsoleRunner/tools/nunit3-console.exe ./FSharp.Data.JsonPath.Tests/bin/Release/FSharp.Data.JsonPath.Tests.dll